### ISSUE TITLE
Merge it with python-socialblade

### ISSUE THREAD

**Issue by meatyite** [3jackdaws/soundcloud-lib#17]
Hey there.
I'm the owner the `socialblade` PyPi package aka python-socialblade. Wondering if we can somehow merge our code, and i'll let this project use the `socialblade` package name on PyPi instead of the stupid `socialblade-lib` thing?
https://github.com/sl4vkek/python-socialblade

**Comment by 3jackdaws** [comment]
I think this issue was opened in error.
