### ISSUE TITLE
the resolve function spams the console

### ISSUE THREAD

**Issue by Darkempire78** [3jackdaws/soundcloud-lib#21]
Hi, i'm using this superb library, but the reolve function spam the console each request. 
It's possible to remove this ?
![image](https://user-images.githubusercontent.com/50015928/104102928-be3eda80-529f-11eb-9495-3b78fedc1bd4.png)

**Comment by clementwzk** [comment]
I use the asyncio version

**Comment by clementwzk** [comment]
fixed!
