### ISSUE TITLE
ModuleNotFoundError: No module named 'sclib'

### ISSUE THREAD

**Issue by CJSparrow** [3jackdaws/soundcloud-lib#23]
i got this error ```ModuleNotFoundError: No module named 'sclib'```, but everything was installed by ```pip install soundcloud-lib``` and ```pip install sclib```

**Comment by CJSparrow** [comment]
Installed by installing soundcloud-lib from GitHub instead of ```pip install soundcloud-lib```. 
You Should fix it guys!

**Comment by 3jackdaws** [comment]
To install this package, only run `pip install soundcloud-lib`. `sclib` is another package entirely.  Ensure that the version of pip you use installs for the correct version of python.

I just confirmed that running `pip install soundcloud-lib` works as intended.

**Comment by CJSparrow** [comment]
> 
> 
> To install this package, only run `pip install soundcloud-lib`. `sclib` is another package entirely. Ensure that the version of pip you use installs for the correct version of python.
> 
> I just confirmed that running `pip install soundcloud-lib` works as intended.

in your examples you used ```sclib ``` as a main library !
however i used pip last version, and i used pip3.8 same error.
also in Linux it does not work at all bc of importing sclib.

**Comment by 3jackdaws** [comment]
Please paste your code

**Comment by CJSparrow** [comment]
> 
> 
> Please paste your code

no need, it's your example 1, in the first page.
you can check the error image [here](https://i.ibb.co/s3k7d1s/1.png), and check installing proof [here](https://i.ibb.co/3BV9gdg/2.png).

**Comment by CJSparrow** [comment]
also i'm sure what version i used for pip or for running the script. it's python 3.9

**Comment by 3jackdaws** [comment]
Can you `pip install soundcloud-lib` then in the same terminal session run `python` and see if you can `import sclib` from the repl?

**Comment by CJSparrow** [comment]
nvm it just work after i reinstall it, sorry for any inconvenience.
