### ISSUE TITLE
SSL error ssl.SSLCertVerificationError:

### ISSUE THREAD

**Issue by ghost** [3jackdaws/soundcloud-lib#4]
I get an SSL error whenever I try to use soundcloud-lib in my python scripts, namely: 
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`
Although I don't think this is coming from your library directly. For anyone having this same issue, I solved this error by adding `import ssl
ssl._create_default_https_context = ssl._create_unverified_context` to my script. I don't know if there's anything you can do @3jackdaws to prevent this error out of the box, or if this is just a problem affecting me.

**Comment by 3jackdaws** [comment]
What OS are you running?

**Comment by ghost** [comment]
OS X

**Comment by 3jackdaws** [comment]
Cool.  I'm sure you found the same fix, but this issue looks like it can be resolved by installing the `certifi` package by default on osx.

**Comment by ghost** [comment]
Will look into it, thanks!

**Comment by jsvh** [comment]
this is still happening, worked fine on dev environment, but once I switch to my opal stack server it gave me the same error. adding the above fix worked!!
